### ISSUE TITLE
Duplicate MySQL entry causing media creation failures

### ISSUE THREAD

**Issue by joecorall** [discoverygarden/islandora_hierarchical_access#22]
I keep running into this issue when creating (derivative) media:

```
Symfony\Component\HttpKernel\Exception\HttpException: SQLSTATE[23000]: Integrity constraint violation: 1062
Duplicate entry '391019-1554891-1557562' for key 'PRIMARY':
INSERT INTO "islandora_hierarchical_access_lut" ("nid", "mid", "fid") SELECT "n"."nid" AS "nid", "m"."mid" AS "mid", COALESCE(fm.fid, 0) AS "fid" FROM "node" "n" INNER JOIN "media__field_media_of" "fmo" ON fmo.field_media_of_target_id = n.nid INNER JOIN "media" "m" ON m.mid = fmo.entity_id LEFT OUTER JOIN "media__field_media_file" "mf" ON mf.entity_id = m.mid LEFT OUTER JOIN "media__field_media_audio_file" "mf_2" ON mf_2.entity_id = m.mid LEFT OUTER JOIN "media__field_media_document" "mf_3" ON mf_3.entity_id = m.mid LEFT OUTER JOIN "media__field_media_image" "mf_4" ON mf_4.entity_id = m.mid LEFT OUTER JOIN "media__field_media_video_file" "mf_5" ON mf_5.entity_id = m.mid LEFT OUTER JOIN "file_managed" "fm" ON fm.fid IN (mf.field_media_file_target_id, mf_2.field_media_audio_file_target_id, mf_3.field_media_document_target_id, mf_4.field_media_image_target_id, mf_5.field_media_video_file_target_id) WHERE "m"."mid" = :db_condition_placeholder_0; Array ( [:db_condition_placeholder_0] => 1554891 )
in Drupal\islandora\Controller\MediaSourceController->putToNode() (line 192 of /var/www/drupal/web/modules/contrib/islandora/src/Controller/MediaSourceController.php).
```

It unfortunately completely fails the media creation. I haven't found a root cause but wanted to report it. I keep just commenting out the relevant code to get around it (which obviously only lasts as long as a given container's lifecycle)

**Comment by joecorall** [comment]
Closing this issue as i won't be able to help push it along any further or help troubleshoot. We ended up just implementing the embargo functionality locally due to this problem and identifying slow queries caused by this module's access handlers (which only manifested in paged content IIIF results).

**Comment by adam-vessey** [comment]
I vaguely recall encountering something of the like with an implementation
of `hook_entity_update()` (or was it `[...]_insert()`?) which was
attempting to modify the passed entity (possibly with an additional
`$entity->save()` call?); however, this is not allowed/supported by Drupal.

That said, it's difficult to really say anything for sure without more of a
stacktrace.

**Comment by joecorall** [comment]
Yeah that could be it for the original problem. But with some xhprof investigation today realized the reason our IIIF manifests were taking minutes to render instead of seconds was a combination of the islandora_iiif module's N number of lookups for OCR files per child along with this module's attached access lookups on each of those queries.
